export const ProductData = [
  {
    id: 1,
    category: "Dog",
    name: "Pedigree Chicken & Vegetables Adult Dog Dry Food",
    src: "https://supertails.com/cdn/shop/products/61wJA-Ph8OL._SX679.jpg?v=1655873823",
    description:
      "Pedigree Chicken & Vegetables Adult Dry Dog Food is a wholesome meal, packed with essential nutrients vital to the healthy growth of your pet. The natural goodness of cereals, soybean, carrots, peas & milk blend into a tasty treat for your little one. It assures healthier and a shinier coat, strong muscles, good digestive health, healthy bones and teeth and a stronger immune system. Pedigree Chicken & Vegetables Adult Dry Dog Food contains special mix of fatty acids for healthy skin and coat.",
    price: "284",
    quantity: 1,
  },
  {
    id: 2,
    category: "Dog",
    name: "Drools Focus Super Premium Adult Dry Dog Food",
    src: "https://supertails.com/cdn/shop/products/1_52f53ec0-b54f-4e8a-ae4e-1489b807d797.jpg?v=1677500944",
    description:
      "Drools Focus Super Premium Adult Dry Dog Food is an all Breed formula. It is a wholesome nutritional meal that ensures all the benefits, ranging from strong immunity to dental health. At Drools, we understand your pet's needs and provide a power packed food that your pet will surely love. Fortified with Vitamins, essential Amino Acids, Minerals, Antioxidants, and other important ingredients, Drools Focus Adult Dry Dog Food provides a complete and balanced food to your pet.",
    price: "534",
    quantity: 1,
  },
  {
    id: 3,
    category: "Dog",
    name: "Royal Canin Maxi Puppy Dog Dry Food (2-15 months)",
    src: "https://supertails.com/cdn/shop/files/Frame12314_89a8f769-48d6-4acd-8f9c-e3e10f1c8577.png?v=1693291989",
    description:
      "ROYAL CANIN® Maxi Puppy is specially formulated with the nutritional needs of your large puppy in mind. This food is suitable for large puppies from 2 to 15 months old that will have an adult weight of approximately 26kg-44kg. ROYAL CANIN® Maxi Puppy food contains a patented complex of antioxidants - including the highly beneficial vitamin E - to support your puppy's natural defences while its immune system is immature and still developing.",
    price: "855",
    quantity: 1,
  },
  {
    id: 4,
    category: "Dog",
    name: "Drools | 100% Vegetarian Adult Dog Dry Food",
    src: "https://supertails.com/cdn/shop/products/Frame10798_1-304171_1800x1800.png?v=1693292839",
    description:
      "Drools 100% vegetarian adult dry dog food is a unique formula consisting of ingredients from plants along with essential nutrients that provide a complete and balanced diet for dog. It combines antioxidants, vitamins and minerals which strengthen joints and keeps digestive system healthy. It also has optimum ratio of omega 6 and 3 fatty acids that helps dog have healthy skin and lustrous coat.",
    price: "645",
    quantity: 1,
  },
  {
    id: 5,
    category: "Cat",
    name: "Sheba Chicken Flavour Cat Dry Food",
    src: "https://supertails.com/cdn/shop/products/6914973706279_6.png?v=1680677806",
    description:
      "Indulge your feline friend with the delicious taste and crunchy texture of Sheba® Dry Cat Food. A magnificent combination of Crunchy kibbles and Creamy Pockets for Cats in Chicken Flavor. With Sheba® Dry Cat Food, your cat can enjoy a satisfying meal that's both delicious and nutritious.",
    price: "1156",
    quantity: 1,
  },
  {
    id: 6,
    category: "Cat",
    name: "Royal Canin Kitten Gravy Wet Food",
    src: "https://supertails.com/cdn/shop/products/Frame10336_4.png?v=1692456346",
    description:
      "Giving your kitten the best start in life all begins with the right nutrition. Providing it with the essential nutrients it needs will properly support your kitten's development and growth at critical stages and beyond. Weaning kittens from their mother's milk can be difficult - particularly if the food isn't specifically tailored to your kitten's needs and palatability. That's why ROYAL CANIN® Kitten Instinctive in Gravy is formulated to match the optimal nutritional profile instinctively preferred by kittens. Feeding your kitten a palatable diet that takes taste, scent and texture into account will lead to long-term, instinctive acceptance of the nutritious food that you provide.",
    price: "489",
    quantity: 1,
  },
  {
    id: 7,
    category: "Cat",
    name: "Purina Felix Tuna with Jelly Kitten Wet Food",
    src: "https://supertails.com/cdn/shop/products/Frame6-2022-12-16T140542.414.png?v=1671182637",
    description:
      "Nestle Purina Felix was introduced in the year 1970 and is already a number one cat food brand in the markets of UK, Germany, Australia and Thailaand Felix As Good as it Looks™ is a range of delicious meals specially prepared with tender meaty pieces in a succulent jelly which look and smell so meaty, it looks like food you have cooked yourself. They are full of healthy goodness to satisfy 100% of your cat's daily needs when fed according to the feeding guidelines on the pack.",
    price: "594",
    quantity: 1,
  },
  {
    id: 8,
    category: "Cat",
    name: "Royal Canin Fit 32 Adult Cat Dry Food",
    src: "https://supertails.com/cdn/shop/products/Supertails_11-compressed.jpg?v=1678453486",
    description: "ROYAL CANIN® Fit 32 is suitable for adult cats between 1-7 years old, it's been specially designed to meet all of your cat's nutritional requirements for supporting and maintaining the healthy situation that your cat is currently in. Your cat needs high quality nutrition to meet all the requirements of adulthood - that's why ROYAL CANIN® Fit 32 has an optimal nutrient profile that contains the right level of beneficial nutrients to help support and maintain the good health of your adult cat.",
    price: "2975",
    quantity: 1,
  },
  {
    id: 9,
    category: "Dog",
    name: "Farmina N&D Chicken & Pomegranate Ancestral Grain Selection",
    src: "https://supertails.com/cdn/shop/products/Frame1_642aeb2a-f2ea-49f5-bb83-d4b225f6df25_1_2.png?v=1680527851",
    description:
      "This food is a grain-free formula that contains ideal levels of EPA-DHA that helps in improving the skin and coat of these dogs. This diet is designed to meet the specific needs of mini breed dogs to promote growth throughout every stage of their life. This diet is rich in glucosamine & chondroitin that also helps in enhancing the bone strength of adult or ageing dogs. This Food is an assortment of all essential ingredients that help in maintaining the high energy level of dogs of these breeds.",
    price: "475",
    quantity: 1,
  },
  {
    id: 10,
    category: "Dog",
    name: "SuperCoat Chicken Adult All Breed Dog Dry Food",
    src: "https://supertails.com/cdn/shop/products/DFODF0003PS_1-compressed.jpg?v=1655889988",
    description:
      "SUPERCOAT is developed by Nestlé Purina experts with 120 years of expertise in pet nutrition. It provides tailored nutrition with precise combination of quality natural ingredients to bring out your dog’s whole body health – both inside & outside. SUPERCOAT Puppy is specially designed to meet the nutritional requirements of growing puppies. It contains DHA that aids your puppy’s brain and vision development, high-quality protein to build his strong immune system; rich in calcium to help strengthen his teeth & bones and contains vitamins E & C to build his natural defenses.",
    price: "760",
    quantity: 1,
  },
  {
    id: 11,
    category: "Dog",
    name: "Pedigree PRO Expert Nutrition for Large Breed Puppy",
    src: "https://supertails.com/cdn/shop/products/8906002484584-1-875407.jpg?v=1693553800",
    description:
      "Different dog breeds have different nutritional needs, depending on their size and respective weight. Large breed puppies such as Golden retriever, German Shephard, Labrador, Dobermann, and St.Bernard grow faster and achieve adulthood earlier, which is why, nutrient rich and protein rich meals like Pedigree PRO are needed to support their growth. It contains Glucosamine & Omega Fatty Acids to help support healthy joints, Controlled Calcium to Phosphorus Ratio to ensure healthy bone development and Prebiotics (MOS) to help promote Digestive health.",
    price: "379",
    quantity: 1,
  },
  {
    id: 12,
    category: "Dog",
    name: "Canine Creek Club Ultra Premium Single Grain Dog Dry Food",
    src: "https://supertails.com/cdn/shop/products/1_49d1069b-14bb-42d8-a5e4-78ef1e4e6cb3_1_1.jpg?v=1655823397",
    description:
      "Canine Creek Club Ultra Premium Dog Food is a life preservative and single grain formula. It is enhanced with 7 antioxidants – Apples, Blackberries, Cranberries, Pomegranate, Pumpkin, Spinach, Blueberries. Canine Creek food is also a manufacturing breakthrough because it is “cold-formed” to minimize the heat the ingredients are exposed to minimizing heat exposure is important because high heat can degrade the potency of many vitamins, minerals, antioxidants and important enzymes.",
    price: "1423",
    quantity: 1,
  },
  {
    id: 13,
    category: "Cat",
    name: "Drools Ocean Fish Adult Cat Dry Food",
    src: "https://supertails.com/cdn/shop/products/Frame88-725378.png?v=1693292844",
    description: "Drools Ocean Fish Adult Cat Dry Food is designed to support cat's vital functions. It provides better vision, a healthy and shiny coat. This complete and balanced meal provides the essential vitamins and minerals which makes cat healthy. Prebiotics (Natural fibres) protect cats from hairball formation and Probiotics keep their digestive system healthy. Omega 3 & 6 fatty acids keep the coat beautiful and lustrous.",
    price: "336",
    quantity: 1,
  },
  {
    id: 14,
    category: "Cat",
    name: "Temptations Seafood Medley Flavour",
    src: "https://supertails.com/cdn/shop/products/SUPERTAILS_7_5037419e-b59e-4226-81d4-8f9255c30d39.jpg?v=1655891621",
    description: "You don't need a particular day to pamper and love your cat; every day can be made theirs with Temptations. Create a brighter world for cats with this cat treat that has a tasty, crunchy outside and an irresistible soft center.",
    price: "414",
    quantity: 1,
  },
  {
    id: 15,
    category: "Cat",
    name: "Me O Adult Persian Dry Cat Food",
    src: "https://supertails.com/cdn/shop/products/Frame6-2022-12-30T163613.942-566283.png?v=1693553236",
    description: "Persian cats have long hair coat that predisposes them to hair ball problems when they swallow hair during grooming. To prevent this problem, Me-O Persian Cat Food incorporates a special fiber that continuously promotes the safe passage of swallowed hair through the digestive tract thereby reducing the risk of hairball formation.",
    price: "912",
    quantity: 1,
  },
  {
    id: 16,
    category: "Cat",
    name: "Friskies Surfin Cat Dry Food",
    src: "https://supertails.com/cdn/shop/products/61f4pG9BaGL1-790332.png?v=1693552106",
    description: "Give your kitty a bowl of nutrition from land and sea with Friskies Surfin' & Turfin' Favorites Dry Cat Food. It packs whisker-licking flavor that’s sure to impress even the pickiest connoisseur, with real chicken, ocean fish, salmon and crab in every crunchy bite. This delicious kitty kibble is loaded with protein to encourage healthy muscles, essential fatty acids to help support healthy skin and coat, vitamin A and taurine to support healthy vision and finally antioxidants to help maintain a healthy immune system.",
    price: "1459",
    quantity: 1,
  },
];
